### ISSUE TITLE
Add operations meta data to resources manager

### ISSUE THREAD

**Issue by ArtemConstantinov** [xenanetworks/open-automation-core#15]
Currently, test resources just distribute changed data but it is not clear what operation was made and what data was before

**Comment by ArtemConstantinov** [comment]
Remains to complete
- [ ] Organize proper imports
- [ ] Save keep_disconnected on failure to add tester at startup time
- [ ] Save keep_disconnected after connection failed and all attempts to reconnect also was unsuccessful
